# Generated by Django 5.2.1 on 2025-06-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_course_user_date_of_birth_user_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='study_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
